import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import * as Sentry from "npm:@sentry/deno@^10";
import { createClient } from "jsr:@supabase/supabase-js@2";

// ─── Sentry init ───────────────────────────────────────────
// Runs once per cold start, idempotent across warm invocations.
// When SENTRY_DSN is unset (local `supabase functions serve` / smoke tests),
// init is a no-op and downstream capture/breadcrumb calls also no-op —
// the instrumentation is strict-additive and never alters the snapshot
// path's behavior. Sample rate matches sentry.server.config.ts (10% prod).
const SENTRY_DSN = Deno.env.get("SENTRY_DSN") ?? "";
const SENTRY_ENVIRONMENT = Deno.env.get("SENTRY_ENVIRONMENT") ?? "production";
if (SENTRY_DSN) {
  Sentry.init({
    dsn: SENTRY_DSN,
    tracesSampleRate: 0.1,
    sendDefaultPii: false,
    environment: SENTRY_ENVIRONMENT,
  });
}

// ─── Config ────────────────────────────────────────────────

// Validated at call time (not at module load) so cold-start failures still
// return a 500 instead of crashing the isolate with an opaque error.
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const COINGECKO_API_KEY = Deno.env.get("COINGECKO_API_KEY") ?? "";

const YAHOO_QUOTE_URL = "https://query1.finance.yahoo.com/v7/finance/quote";
const YAHOO_CHART_URL = "https://query1.finance.yahoo.com/v8/finance/chart";
const COINGECKO_URL = "https://api.coingecko.com/api/v3/simple/price";
const FRANKFURTER_URL = "https://api.frankfurter.dev/v1/latest";

// ─── Fetch timeout (matches app-side fetchWithTimeout pattern) ──

async function fetchT(url: string | URL | Request, init?: RequestInit, timeoutMs = 15_000): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
}

// ─── Types ─────────────────────────────────────────────────

interface UserHoldings {
  userId: string;
  cryptoAssets: { coingecko_id: string; subcategory: string | null; quantity: number }[];
  stockAssets: { asset_id: string; yahoo_ticker: string; ticker: string; currency: string; quantity: number; kind: "yahoo" | "manual" }[];
  cashItems: { currency: string; amount: number }[];
}

interface YahooQuote {
  price: number;
  currency: string;
}

// ─── Main handler ──────────────────────────────────────────

Deno.serve(async (req: Request) => {
  // Validate required env vars at call time so misconfigured deploys
  // surface as HTTP 500 "Misconfigured" rather than isolate crashes.
  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    console.error("[daily-snapshot] Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY env var");
    return new Response("Misconfigured", { status: 500 });
  }

  // Fast reject before the DB round-trip when the caller didn't supply any
  // bearer credentials — this avoids wasting a query on health probes
  // and unauthenticated scans.
  const authHeader = req.headers.get("Authorization") ?? "";
  if (!authHeader.startsWith("Bearer ")) {
    return new Response("Unauthorized", { status: 401 });
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

  // Auth check — read secret from DB (auto-generated by migration 052, never in git)
  const { data: configRow } = await supabase
    .from("cron_config")
    .select("value")
    .eq("key", "cron_secret")
    .single();

  if (!configRow?.value || authHeader !== `Bearer ${configRow.value}`) {
    return new Response("Unauthorized", { status: 401 });
  }

  // Per-invocation correlation: lets operators trace a single cron tick
  // across all Sentry events, Supabase logs, and the HTTP response payload.
  // Each Deno.serve invocation runs in its own async context, so tags set
  // here are scoped to this invocation via Sentry's OTel context manager.
  const runId = crypto.randomUUID();
  Sentry.setTag("function", "daily-snapshot");
  Sentry.setTag("cron_run_id", runId);
  const startedAt = Date.now();

  try {

    // 1. Fetch all active users
    const { data: users, error: usersErr } = await supabase
      .from("profiles")
      .select("id")
      .eq("status", "active");

    if (usersErr) throw new Error(`Failed to fetch users: ${usersErr.message}`);
    if (!users || users.length === 0) {
      await Sentry.flush(2000);
      return jsonResponse({ message: "No active users", snapshots: 0, runId });
    }

    Sentry.addBreadcrumb({
      category: "snapshot",
      message: "Active users loaded",
      data: { count: users.length },
      level: "info",
    });

    const userIds = users.map((u: { id: string }) => u.id);

    // 2. Bulk-fetch all holdings across all users (service-role bypasses RLS)
    const [
      { data: cryptoAssets },
      { data: cryptoPositions },
      { data: stockAssets },
      { data: stockPositions },
      { data: cashAccounts },
    ] = await Promise.all([
      supabase.from("crypto_assets").select("id, user_id, coingecko_id, subcategory").is("deleted_at", null).in("user_id", userIds),
      supabase.from("crypto_positions").select("id, crypto_asset_id, quantity").is("deleted_at", null),
      supabase.from("stock_assets").select("id, user_id, ticker, yahoo_ticker, currency, kind").is("deleted_at", null).in("user_id", userIds),
      supabase.from("stock_positions").select("id, stock_asset_id, quantity").is("deleted_at", null),
      supabase.from("cash_accounts").select("user_id, currency, balance").is("deleted_at", null).in("user_id", userIds),
    ]);

    // 3. Build per-user holdings and deduplicated price request sets
    const coinIdSet = new Set<string>();
    const yahooTickerSet = new Set<string>();
    const currencySet = new Set<string>(["USD", "EUR"]);

    // Index crypto positions by asset ID
    const positionsByAsset = new Map<string, number>();
    for (const p of cryptoPositions ?? []) {
      const current = positionsByAsset.get(p.crypto_asset_id) ?? 0;
      positionsByAsset.set(p.crypto_asset_id, current + Number(p.quantity));
    }

    // Index stock positions by asset ID
    const stockPosByAsset = new Map<string, number>();
    for (const p of stockPositions ?? []) {
      const current = stockPosByAsset.get(p.stock_asset_id) ?? 0;
      stockPosByAsset.set(p.stock_asset_id, current + Number(p.quantity));
    }

    // Build per-user holdings
    const userHoldings = new Map<string, UserHoldings>();
    for (const userId of userIds) {
      userHoldings.set(userId, {
        userId,
        cryptoAssets: [],
        stockAssets: [],
        cashItems: [],
      });
    }

    // Crypto assets
    for (const asset of cryptoAssets ?? []) {
      const qty = positionsByAsset.get(asset.id) ?? 0;
      if (qty === 0) continue;
      coinIdSet.add(asset.coingecko_id);
      const holdings = userHoldings.get(asset.user_id);
      if (holdings) {
        holdings.cryptoAssets.push({
          coingecko_id: asset.coingecko_id,
          subcategory: asset.subcategory,
          quantity: qty,
        });
      }
    }

    // Stock assets — kind='yahoo' get added to yahooTickerSet for the Yahoo batch;
    // kind='manual' are looked up from manual_nav_updates below (no Yahoo fetch).
    for (const asset of stockAssets ?? []) {
      const qty = stockPosByAsset.get(asset.id) ?? 0;
      if (qty === 0) continue;
      const kind = (asset.kind as "yahoo" | "manual") ?? "yahoo";
      const yahooTicker = asset.yahoo_ticker || asset.ticker;
      if (kind === "yahoo") {
        yahooTickerSet.add(yahooTicker);
      }
      currencySet.add(asset.currency);
      const holdings = userHoldings.get(asset.user_id);
      if (holdings) {
        holdings.stockAssets.push({
          asset_id: asset.id,
          yahoo_ticker: yahooTicker,
          ticker: asset.ticker,
          currency: asset.currency,
          quantity: qty,
          kind,
        });
      }
    }

    // Cash items (unified cash_accounts table)
    for (const acct of cashAccounts ?? []) {
      const amt = Number(acct.balance);
      if (amt === 0) continue;
      currencySet.add(acct.currency);
      const holdings = userHoldings.get(acct.user_id);
      if (holdings) holdings.cashItems.push({ currency: acct.currency, amount: amt });
    }

    // 4. Batch price fetches (4 API calls in parallel)
    const allTickers = [...yahooTickerSet];
    const nonUsdEurCurrencies = [...currencySet].filter((c) => c !== "USD" && c !== "EUR");
    const settled = await Promise.allSettled([
      fetchCoinGeckoPrices([...coinIdSet]),
      fetchYahooBatch(allTickers),
      fetchFxRates("USD", [...currencySet].filter((c) => c !== "USD")),
      fetchFxRates("EUR", [...currencySet].filter((c) => c !== "EUR")),
    ]);
    const [cryptoSettled, yahooSettled, fxUsdSettled, fxEurSettled] = settled;

    // When FX fetches fail but users hold non-USD/non-EUR assets (GBP, CHF,
    // etc.), falling back to `{ USD: 1 }` produces a silently-corrupt
    // snapshot because `convertToBase()` returns the unconverted native
    // amount labelled as USD. Refuse to proceed in that case — partial
    // snapshots for USD/EUR-only users are still fine.
    const fxUsdFailed = fxUsdSettled.status === "rejected";
    const fxEurFailed = fxEurSettled.status === "rejected";
    if ((fxUsdFailed || fxEurFailed) && nonUsdEurCurrencies.length > 0) {
      const reason = fxUsdFailed
        ? (fxUsdSettled as PromiseRejectedResult).reason
        : (fxEurSettled as PromiseRejectedResult).reason;
      console.error(
        `[daily-snapshot] FX fetch failed with non-USD/EUR currencies in scope (${nonUsdEurCurrencies.join(",")}) — aborting to avoid corrupt snapshots.`,
        reason,
      );
      Sentry.captureMessage(
        "Daily snapshot aborted: FX fetch failed with non-USD/EUR currencies in scope",
        {
          level: "error",
          extra: {
            fxUsdFailed,
            fxEurFailed,
            currencies: nonUsdEurCurrencies,
            reason: String(reason),
          },
        },
      );
      await Sentry.flush(2000);
      return jsonResponse(
        { error: "fx_unavailable", currencies: nonUsdEurCurrencies, runId },
        503,
      );
    }

    const cryptoPrices = cryptoSettled.status === "fulfilled"
      ? cryptoSettled.value
      : ({} as Record<string, { usd: number; eur: number }>);
    const yahooQuotes = yahooSettled.status === "fulfilled"
      ? yahooSettled.value
      : new Map<string, YahooQuote>();
    const fxUsd = fxUsdSettled.status === "fulfilled"
      ? fxUsdSettled.value
      : ({ USD: 1 } as Record<string, number>);
    const fxEur = fxEurSettled.status === "fulfilled"
      ? fxEurSettled.value
      : ({ EUR: 1 } as Record<string, number>);

    // 4b. Fall back to v8/chart for any tickers missing from v7 batch.
    // Bail out of the remaining chunks if cumulative elapsed time approaches
    // the Edge Function wall-clock budget — partial ticker coverage is
    // preferable to the whole run timing out.
    const missingTickers = allTickers.filter((t) => !yahooQuotes.has(t));
    const v8StartedAt = Date.now();
    const V8_BUDGET_MS = 90_000; // generous cap well under platform 150s free limit
    if (missingTickers.length > 0) {
      console.log(`[daily-snapshot] v7 missing ${missingTickers.length} tickers, falling back to v8/chart`);
      const CHUNK_SIZE = 20;
      for (let i = 0; i < missingTickers.length; i += CHUNK_SIZE) {
        if (Date.now() - v8StartedAt > V8_BUDGET_MS) {
          const remaining = missingTickers.length - i;
          console.warn(`[daily-snapshot] v8 fallback budget exhausted — skipping ${remaining} tickers`);
          Sentry.addBreadcrumb({
            category: "yahoo",
            message: "v8 fallback budget exhausted",
            data: { processed: i, skipped: remaining, totalMissing: missingTickers.length },
            level: "warning",
          });
          break;
        }
        const chunk = missingTickers.slice(i, i + CHUNK_SIZE);
        const results = await Promise.allSettled(
          chunk.map((ticker) => fetchYahooSingle(ticker))
        );
        results.forEach((result, j) => {
          if (result.status === "fulfilled" && result.value) {
            yahooQuotes.set(chunk[j], result.value);
          }
        });
      }
    }

    // 5. Compute snapshots for each user
    const today = new Date().toISOString().split("T")[0];

    // Fetch latest manual NAV per (user_id, asset_id) as of `today`. Service-
    // role bypasses RLS so a single batched query covers all users. JS-side
    // groupBy keeps "max effective_date per (user, asset)" since the SQL
    // function get_latest_manual_navs_at takes a single user_id per call.
    // Defense: destructure and throw on error so a silent fetch failure
    // doesn't silently write wrong snapshots (manual contributions = 0) to
    // the entire fleet on the day the query breaks.
    const { data: manualNavsRaw, error: manualNavsErr } = await supabase
      .from("manual_nav_updates")
      .select("user_id, asset_id, effective_date, nav")
      .lte("effective_date", today)
      .in("user_id", userIds);

    if (manualNavsErr) {
      throw new Error(`Failed to load manual NAV history for cron: ${manualNavsErr.message}`);
    }

    const manualNavByUserAsset = new Map<string, number>(); // `${user_id}:${asset_id}` → latest nav
    const manualNavMaxDate = new Map<string, string>();
    for (const row of (manualNavsRaw ?? [])) {
      const key = `${row.user_id}:${row.asset_id}`;
      const prevDate = manualNavMaxDate.get(key);
      if (!prevDate || row.effective_date > prevDate) {
        manualNavMaxDate.set(key, row.effective_date);
        manualNavByUserAsset.set(key, Number(row.nav));
      }
    }
    const snapshots: {
      user_id: string;
      snapshot_date: string;
      total_value_usd: number;
      total_value_eur: number;
      crypto_value_usd: number;
      stocks_value_usd: number;
      cash_value_usd: number;
      crypto_value_eur: number;
      stocks_value_eur: number;
      cash_value_eur: number;
      stocks_eur_denominated_value: number;
      cash_eur_denominated_value: number;
    }[] = [];

    for (const [userId, holdings] of userHoldings) {
      let cryptoValueUsd = 0;
      let cryptoValueEur = 0;
      let stablecoinValueUsd = 0;
      let stablecoinValueEur = 0;

      // Crypto values (CoinGecko gives USD + EUR directly)
      for (const asset of holdings.cryptoAssets) {
        const price = cryptoPrices[asset.coingecko_id];
        if (!price) continue;
        const isStable = asset.subcategory?.toLowerCase() === "stablecoin";
        if (isStable) {
          stablecoinValueUsd += asset.quantity * (price.usd ?? 0);
          stablecoinValueEur += asset.quantity * (price.eur ?? 0);
        } else {
          cryptoValueUsd += asset.quantity * (price.usd ?? 0);
          cryptoValueEur += asset.quantity * (price.eur ?? 0);
        }
      }

      // Stock values (convert native currency → USD and EUR via FX).
      // kind='yahoo' → look up yahooQuotes (batch-fetched);
      // kind='manual' → look up latest NAV from manual_nav_updates.
      // Assets with no NAV history yet (manual+empty) silently contribute 0.
      let stocksValueUsd = 0;
      let stocksValueEur = 0;
      let stocksHomeCurrencyEur = 0;
      for (const asset of holdings.stockAssets) {
        let priceNative: number | undefined;
        // Exhaustive dispatch on kind. The default branch should never fire
        // (DB CHECK in migration 018 enforces kind in {'yahoo','manual'}),
        // but defense-in-depth: an unknown kind silently skips the asset and
        // emits a log line for operational visibility instead of misrouting
        // to Yahoo / manual paths.
        switch (asset.kind) {
          case "manual":
            priceNative = manualNavByUserAsset.get(`${holdings.userId}:${asset.asset_id}`);
            break;
          case "yahoo":
            priceNative = yahooQuotes.get(asset.yahoo_ticker)?.price;
            break;
          default:
            console.warn(`[daily-snapshot] Unknown stock asset kind="${asset.kind}" for user ${holdings.userId}, asset ${asset.asset_id}; skipping`);
            Sentry.captureMessage("Unknown stock asset kind — DB CHECK invariant violated", {
              level: "error",
              extra: {
                kind: asset.kind,
                userId: holdings.userId,
                assetId: asset.asset_id,
                ticker: asset.ticker,
              },
            });
            continue;
        }
        if (priceNative === undefined) continue;
        const valueNative = asset.quantity * priceNative;
        stocksValueUsd += convertToBase(valueNative, asset.currency, "USD", fxUsd);
        stocksValueEur += convertToBase(valueNative, asset.currency, "EUR", fxEur);
        if (asset.currency === "EUR") {
          stocksHomeCurrencyEur += convertToBase(valueNative, asset.currency, "EUR", fxEur);
        }
      }

      // Cash values (convert each currency → USD and EUR via FX)
      let fiatCashValueUsd = 0;
      let fiatCashValueEur = 0;
      let cashHomeCurrencyEur = 0;
      for (const item of holdings.cashItems) {
        fiatCashValueUsd += convertToBase(item.amount, item.currency, "USD", fxUsd);
        fiatCashValueEur += convertToBase(item.amount, item.currency, "EUR", fxEur);
        if (item.currency === "EUR") {
          cashHomeCurrencyEur += convertToBase(item.amount, item.currency, "EUR", fxEur);
        }
      }

      // Cash = fiat + stablecoins (matching aggregate.ts logic)
      const cashValueUsd = fiatCashValueUsd + stablecoinValueUsd;
      const totalValueUsd = cryptoValueUsd + stocksValueUsd + cashValueUsd;
      const totalValueEur = cryptoValueEur + stocksValueEur + fiatCashValueEur + stablecoinValueEur;

      // Validation: component sum must match total (catches computation bugs)
      const roundedTotal = round2(totalValueUsd);
      const componentSum = round2(cryptoValueUsd + stocksValueUsd + cashValueUsd);
      const drift = Math.abs(roundedTotal - componentSum);
      if (drift > 1) {
        console.error(
          `[daily-snapshot] VALIDATION FAILED for ${userId}: total ($${roundedTotal}) ≠ components ($${componentSum}), drift $${drift}`
        );
        Sentry.captureMessage("Snapshot validation drift exceeded $1", {
          level: "error",
          extra: {
            userId,
            total: roundedTotal,
            componentSum,
            drift,
          },
        });
      }

      const hasHoldings = holdings.cryptoAssets.length > 0 || holdings.stockAssets.length > 0 || holdings.cashItems.length > 0;
      if (totalValueUsd === 0 && hasHoldings) {
        console.warn(
          `[daily-snapshot] SKIPPING ${userId}: $0 total but has holdings (crypto=${holdings.cryptoAssets.length}, stocks=${holdings.stockAssets.length}, cash=${holdings.cashItems.length}) — likely API failure`
        );
        Sentry.captureMessage("Snapshot skipped: $0 total with holdings (likely API failure)", {
          level: "warning",
          extra: {
            userId,
            cryptoCount: holdings.cryptoAssets.length,
            stockCount: holdings.stockAssets.length,
            cashCount: holdings.cashItems.length,
          },
        });
        continue;
      }

      snapshots.push({
        user_id: userId,
        snapshot_date: today,
        created_at: new Date().toISOString(),
        total_value_usd: round2(totalValueUsd),
        total_value_eur: round2(totalValueEur),
        crypto_value_usd: round2(cryptoValueUsd),
        stocks_value_usd: round2(stocksValueUsd),
        cash_value_usd: round2(cashValueUsd),
        crypto_value_eur: round2(cryptoValueEur),
        stocks_value_eur: round2(stocksValueEur),
        cash_value_eur: round2(fiatCashValueEur + stablecoinValueEur),
        stocks_eur_denominated_value: round2(stocksHomeCurrencyEur),
        cash_eur_denominated_value: round2(cashHomeCurrencyEur),
      });
    }

    // 6. Batch upsert all snapshots
    if (snapshots.length > 0) {
      const { error: upsertErr } = await supabase
        .from("portfolio_snapshots")
        .upsert(snapshots, { onConflict: "user_id,snapshot_date" });

      if (upsertErr) throw new Error(`Upsert failed: ${upsertErr.message}`);
    }

    Sentry.addBreadcrumb({
      category: "snapshot",
      message: "Snapshots upserted",
      data: {
        count: snapshots.length,
        coins: coinIdSet.size,
        stocks: yahooTickerSet.size,
        currencies: currencySet.size,
        v8Fallback: missingTickers.length,
        elapsedMs: Date.now() - startedAt,
      },
      level: "info",
    });
    await Sentry.flush(2000);

    return jsonResponse({
      message: "Snapshots saved",
      snapshots: snapshots.length,
      prices: { coins: coinIdSet.size, stocks: yahooTickerSet.size, currencies: currencySet.size },
      v8Fallback: missingTickers.length,
      runId,
    });
  } catch (err) {
    Sentry.captureException(err);
    console.error(`[daily-snapshot] Error (run ${runId}):`, err);
    await Sentry.flush(2000);
    return jsonResponse({ error: String(err), runId }, 500);
  }
});

// ─── Price fetchers ────────────────────────────────────────

async function fetchCoinGeckoPrices(
  coinIds: string[]
): Promise<Record<string, { usd: number; eur: number }>> {
  if (coinIds.length === 0) return {};
  try {
    const ids = coinIds.join(",");
    const url = `${COINGECKO_URL}?ids=${ids}&vs_currencies=usd,eur`;
    const headers: Record<string, string> = {};
    if (COINGECKO_API_KEY) headers["x-cg-demo-api-key"] = COINGECKO_API_KEY;

    let res = await fetchT(url, { headers });
    if (res.status === 429) {
      console.warn("[daily-snapshot] CoinGecko 429, retrying in 2s…");
      await new Promise((r) => setTimeout(r, 2000));
      res = await fetchT(url, { headers });
    }
    if (!res.ok) {
      console.error("[daily-snapshot] CoinGecko error:", res.status);
      return {};
    }
    return await res.json();
  } catch (err) {
    console.error("[daily-snapshot] CoinGecko fetch error:", err);
    return {};
  }
}

async function getYahooCrumb(): Promise<{ crumb: string; cookie: string } | null> {
  try {
    // Step 1: Get session cookies
    const cookieRes = await fetchT("https://fc.yahoo.com/", {
      headers: { "User-Agent": "Mozilla/5.0" },
      redirect: "manual",
    });
    const setCookies = cookieRes.headers.getSetCookie?.() ?? [];
    const cookie = setCookies.map((c) => c.split(";")[0]).filter(Boolean).join("; ");
    if (!cookie) return null;

    // Step 2: Exchange cookies for crumb
    const crumbRes = await fetchT("https://query2.finance.yahoo.com/v1/test/getcrumb", {
      headers: { "User-Agent": "Mozilla/5.0", Cookie: cookie },
    });
    if (!crumbRes.ok) return null;
    const crumb = await crumbRes.text();
    if (!crumb || crumb.includes("Unauthorized")) return null;

    return { crumb, cookie };
  } catch (err) {
    console.error("[daily-snapshot] Yahoo crumb error:", err);
    return null;
  }
}

async function fetchYahooBatch(
  symbols: string[]
): Promise<Map<string, YahooQuote>> {
  const map = new Map<string, YahooQuote>();
  if (symbols.length === 0) return map;
  try {
    const auth = await getYahooCrumb();
    if (!auth) {
      console.error("[daily-snapshot] Yahoo crumb auth failed");
      return map;
    }

    const url = `${YAHOO_QUOTE_URL}?symbols=${symbols.join(",")}&crumb=${encodeURIComponent(auth.crumb)}`;
    const res = await fetchT(url, {
      headers: { "User-Agent": "Mozilla/5.0", Cookie: auth.cookie },
    });
    if (!res.ok) {
      console.error("[daily-snapshot] Yahoo error:", res.status);
      return map;
    }
    const ct = res.headers.get("content-type") ?? "";
    if (!ct.includes("application/json")) {
      console.warn("[daily-snapshot] Yahoo batch returned non-JSON (captcha?), content-type:", ct);
      return map;
    }
    const json = await res.json();
    const quotes = json?.quoteResponse?.result;
    if (!Array.isArray(quotes)) return map;

    for (const q of quotes) {
      if (!q.symbol) continue;
      map.set(q.symbol, {
        price: q.regularMarketPrice ?? 0,
        currency: q.currency ?? "USD",
      });
    }
  } catch (err) {
    console.error("[daily-snapshot] Yahoo fetch error:", err);
  }
  return map;
}

async function fetchYahooSingle(ticker: string): Promise<YahooQuote | null> {
  try {
    const url = `${YAHOO_CHART_URL}/${encodeURIComponent(ticker)}?interval=1d&range=1d`;
    const res = await fetchT(url, {
      headers: { "User-Agent": "Mozilla/5.0" },
    });
    if (!res.ok) return null;
    const ct = res.headers.get("content-type") ?? "";
    if (!ct.includes("application/json")) return null;
    const json = await res.json();
    const meta = json?.chart?.result?.[0]?.meta;
    if (!meta) return null;
    return {
      price: meta.regularMarketPrice ?? 0,
      currency: meta.currency ?? "USD",
    };
  } catch (err) {
    console.error(`[daily-snapshot] v8 fallback error for ${ticker}:`, err);
    return null;
  }
}

async function fetchFxRates(
  base: string,
  targets: string[]
): Promise<Record<string, number>> {
  const symbols = [...new Set(targets.filter((t) => t !== base))];
  if (symbols.length === 0) return { [base]: 1 };

  // Retry once on failure, then throw — snapshot with wrong FX is worse than no snapshot
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const url = `${FRANKFURTER_URL}?base=${base}&symbols=${symbols.join(",")}`;
      const res = await fetchT(url);
      if (!res.ok) {
        if (attempt === 0) {
          console.warn(`[daily-snapshot] Frankfurter ${res.status}, retrying...`);
          continue;
        }
        throw new Error(`Frankfurter API returned ${res.status} for ${base}→${symbols.join(",")}`);
      }
      const data = await res.json();

      // Validate all requested rates are present
      for (const sym of symbols) {
        if (data.rates[sym] == null) {
          throw new Error(`Frankfurter returned no rate for ${base}→${sym}`);
        }
      }

      return { ...data.rates, [base]: 1 };
    } catch (err) {
      if (attempt === 0 && err instanceof TypeError) {
        console.warn("[daily-snapshot] FX network error, retrying...");
        continue;
      }
      throw err;
    }
  }

  throw new Error(`[daily-snapshot] FX retries exhausted for ${base}→${symbols.join(",")}`);
}

// ─── Helpers ───────────────────────────────────────────────

function convertToBase(
  amount: number,
  fromCurrency: string,
  baseCurrency: string,
  rates: Record<string, number>
): number {
  if (fromCurrency === baseCurrency) return amount;
  const rate = rates[fromCurrency];
  if (!rate || rate === 0) {
    console.error(`[daily-snapshot] CRITICAL: no FX rate for ${fromCurrency}→${baseCurrency}, returning unconverted value (SNAPSHOT WILL BE INACCURATE)`);
    return amount;
  }
  // rates[X] = X per 1 base → base = amount / rates[X]
  return amount / rate;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function jsonResponse(body: Record<string, unknown>, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}
